[package]
name = "collision"
version = "0.0.4"
authors = ["Colin Sherratt"]
license = "Apache 2"
description = "A Collision detection library derived from cgmath"

[dependencies]
rustc-serialize="*"
cgmath="*"
